const CONSTANTS = Object.freeze({
    SHOW : 'SHOW',
    DESCRIBE: 'DESCRIBE',
    BINARY: 'BINARY',
    FIELDS : 'FIELDS',
    COLUMNS : 'COLUMNS',
    TABLES : 'TABLES',
    WHERE : 'WHERE',
    BETWEEN : 'BETWEEN',
    NOT_BETWEEN : 'NOT BETWEEN',
    AND : 'AND',
    NULL : 'NULL',
    IS_NULL: 'IS NULL',
    IS_NOT_NULL:'IS NOT NULL',
    OR : 'OR',
    LIKE : 'LIKE',
    SELECT : 'SELECT',
    DISTINCT : 'DISTINCT',
    FROM : 'FROM',
    OFFSET : 'OFFSET',
    GROUP_BY : 'GROUP BY',
    GROUP_CONCAT:'GROUP_CONCAT',
    ORDER_BY : 'ORDER BY',
    DESC : 'DESC',
    ASC : 'ASC',
    INNER_JOIN : 'INNER JOIN',
    LEFT_JOIN : 'LEFT JOIN',
    RIGHT_JOIN : 'RIGHT JOIN',
    CROSS_JOIN : 'CROSS JOIN',
    ON : 'ON',
    LIMIT : 'LIMIT',
    HAVING : 'HAVING',
    COUNT : 'COUNT',
    AVG : 'AVG',
    SUM: 'SUM',
    MAX: 'MAX',
    MIN: 'MIN',
    AS : 'AS',
    EQ : '=',
    NOT_EQ : '!=',
    IN : 'IN',
    NOT_IN : 'NOT IN',
    ALL :'ALL',
    ANY :'ANY',
    SET : 'SET',
    NOT : 'NOT',
    DUPLICATE : 'DUPLICATE',
    KEY :'KEY',
    RAW : '$RAW:',
    OP : '$OP:',
    FREEZE : '$FREEZE:',
    VALUE : '$VALUE:',
    IGNORE : '$IGNORE',
    WHEN : 'WHEN',
    THEN : 'THEN',
    ELSE : 'ELSE',
    CASE : 'CASE',
    END : 'END',
    WHERE_NOT_EXISTS : 'WHERE NOT EXISTS',
    EXISTS :'EXISTS',
    VALUES : 'VALUES',
    UPDATE : 'UPDATE',
    DELETE : 'DELETE',
    INSERT : 'INSERT INTO',
    DROP_DATABASE : 'DROP DATABASE',
    DROP_TABLE : 'DROP TABLE',
    DROP_VIEW: 'DROP VIEW IF EXISTS',
    TRUNCATE_TABLE : 'TRUNCATE TABLE',
    CREATE_DATABASE : 'CREATE DATABASE',
    CREATE_VIEW: 'CREATE VIEW',
    SHOW_DATABASES  : 'SHOW DATABASES',
    SHOW_TABLES : 'SHOW TABLES',
    CREATE_DATABASE_NOT_EXISTS : 'CREATE DATABASE IF NOT EXISTS',
    CREATE_TABLE : 'CREATE TABLE',
    CREATE_TABLE_NOT_EXISTS : 'CREATE TABLE IF NOT EXISTS',
    CREATE_INDEX : 'CREATE INDEX',
    ENGINE:'ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4',
    DEFAULT: 'DEFAULT',
    RAND : 'RAND()',
    AUTO_INCREMENT: 'AUTO_INCREMENT',
    PRIMARY_KEY : 'PRIMARY KEY',
    FOREIGN_KEY : 'FOREIGN KEY',
    REFERENCES : 'REFERENCES',
    ON_DELETE : 'ON DELETE',
    ON_UPDATE : 'ON UPDATE',
    ADD : 'ADD',
    CHANGE : 'CHANGE',
    ADD_CONSTRAINT : 'ADD CONSTRAINT',
    AFTER : 'AFTER',
    ALTER_TABLE : 'ALTER TABLE',
    ALTER_COLUMN: 'ALTER COLUMN',
    IFNULL : 'IFNULL',
    JSON_ARRAY : 'JSON_ARRAY',
    JSON_ARRAYAGG : 'JSON_ARRAYAGG',
    JSON_OBJECT : 'JSON_OBJECT',
    UNION : 'UNION',
    UNION_ALL : 'UNION ALL',
    WITH: 'WITH',
    COALESCE: 'COALESCE',
    NULLIF: 'NULLIF',
    INFORMATION_SCHEMA: 'INFORMATION_SCHEMA',
    STATISTICS: 'STATISTICS',
    RELATIONSHIP : {
        hasOne : 'hasOne',
        hasMany : 'hasMany',
        belongsTo : 'belongsTo',
        belongsToMany : 'belongsToMany',
        belongsToManySingle : 'belongsToManySingle'
    },
    PATTERN : {
        default : 'default',
        snake_case : 'snake_case',
        camelCase : 'camelCase'
    },
    ROW_LEVEL_LOCK : {
        update : 'FOR UPDATE',
        share  : 'LOCK IN SHARE MODE'
    }
})

export { CONSTANTS }
export default CONSTANTS